export const site = {
  name: "Divyansh Shakya",
  brand: "divyansh.dev",
  url: "https://divyansh.dev.gohack.xyz",
  title: "Divyansh Shakya | Cybersecurity Student & Developer",
  description:
    "Portfolio of Divyansh Shakya, a B.Tech CSE (Cybersecurity) student focused on AI security, cloud security, DevSecOps, ethical hacking, and full-stack development.",
  keywords: [
    "Divyansh Shakya",
    "Divyansh Shakya portfolio",
    "cybersecurity student",
    "DevSecOps",
    "cloud security",
    "ethical hacking",
    "full-stack developer",
    "Bhopal",
    "India",
  ],
  profiles: [
    "https://github.com/divyanshakya966",
    "https://linkedin.com/in/divyanshakya966",
    "https://hashnode.com/@divyanshakya966",
    "https://tryhackme.com/p/divyanshakya966",
    "https://profile.hackthebox.com/profile/019c5d4a-8b27-718b-baa5-4597358c866b",
    "https://leetcode.com/u/divyanshakya966",
    "https://x.com/divyanshakya966",
  ],
  image: "/og-image.png",
  imageAlt: "Divyansh Shakya portfolio preview card",
} as const;
